### ISSUE TITLE
PlaySound() changed in 7.3, breakage ensues

### ISSUE THREAD

**Issue by Gnarfoz** [Kruithne/TalkLess#1]
Hi Kru,

as someone pointed out on Curse.com comments (but their notification system sucks), the way this addon uses PlaySound() no longer works in 7.3.
For reference: http://www.wowinterface.com/forums/showthread.php?t=55536 

(Basically, replace all PlaySound("SoundName") with "PlaySound(1234)", with the relevant IDs, to be gleaned from https://www.townlong-yak.com/framexml/live/SoundKitConstants.lua)

Thanks!

**Comment by Kruithne** [comment]
Thanks for reporting this. The cause of the issue was as you said, although TalkLess was already using sound IDs rather than strings, but the API call `PlaySoundKitID` that was used has been removed, in favor of the new functionality behind `PlaySound`.

**Comment by Gnarfoz** [comment]
Yeah, nobody understands why they didn't just remove PlaySound instead... Thanks for the quick fix!
