### ISSUE TITLE
Project labeled as Abandoned on curseforge

### ISSUE THREAD

**Issue by jobackman** [Kruithne/TalkLess#3]
The addon seems to have been labeled as abandoned on curseforge, and the user attributed to the addon is now _Forge_User_93011939_. 

https://www.curseforge.com/wow/addons/talk-less

Is this due to inactivity or is it actually abandoned? AFAIK it still works fine in shadowlands, it just needs a TOC update

**Comment by Kruithne** [comment]
Hey, this is caused by inactivity. I'm not currently maintaining add-ons via CurseForge, only intermittently on GitHub. I've accepted your PR to bump the client version in the TOC, thanks!
